# Generated by Django 2.2.4 on 2022-09-14 19:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounddb', '0002_rdkit_cartridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('mibigAccession', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('genbankAccession', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sequence', models.TextField()),
                ('knownProductSmiles', models.TextField()),
                ('knownProductMCS', models.TextField()),
                ('knownProductSource', models.TextField(default='unknown')),
                ('reviewed', models.BooleanField(default=False)),
                ('notes', models.TextField(default='There are no notes available for this cluster. ')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('stop', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='A',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('substrate', models.CharField(choices=[('thr', 'thr'), ('prop', 'prop'), ('isoval', 'isoval'), ('me-pro', 'me-pro'), ('2aminopent', '2aminopent'), ('dab', 'dab'), ('6-me-hexyl-thr', '6-me-hexyl-thr'), ('phe', 'phe'), ('beta-amino-phe', 'beta-amino-phe'), ('d-arg', 'd-arg'), ('d-cys', 'd-cys'), ('cemal', 'cemal'), ('AAnon', 'AAnon'), ('aba', 'aba'), ('10C-FA', '10C-FA'), ('beta-OH-tyr', 'beta-OH-tyr'), ('N-OH-orn', 'N-OH-orn'), ('mxmal_ACP', 'mxmal_ACP'), ('ema', 'ema'), ('orn', 'orn'), ('CHC-CoA', 'CHC-CoA'), ('butylguanidine', 'butylguanidine'), ('mthz', 'mthz'), ('asp', 'asp'), ('pro', 'pro'), ('isobutmal', 'isobutmal'), ('hpla', 'hpla'), ('me-PABA', 'me-PABA'), ('3measp', '3measp'), ('fatty_acid', 'fatty_acid'), ('cremimycin1', 'cremimycin1'), ('mxmal', 'mxmal'), ('arg', 'arg'), ('d-val', 'd-val'), ('ile', 'ile'), ('trp', 'trp'), ('beta-OH-asn', 'beta-OH-asn'), ('bmt', 'bmt'), ('8C-AA', '8C-AA'), ('asn', 'asn'), ('mal', 'mal'), ('htyr', 'htyr'), ('ethylguanidine', 'ethylguanidine'), ('d-gln', 'd-gln'), ('cyclopentene', 'cyclopentene'), ('d-met', 'd-met'), ('d-pro', 'd-pro'), ('piperazic', 'piperazic'), ('NH2', 'NH2'), ('16C-FA', '16C-FA'), ('d-phe', 'd-phe'), ('cys', 'cys'), ('PABA', 'PABA'), ('3aminobut', '3aminobut'), ('D-isobutmal', 'D-isobutmal'), ('glu', 'glu'), ('mpro', 'mpro'), ('val', 'val'), ('hexmal', 'hexmal'), ('ala', 'ala'), ('end', 'end'), ('hmal', 'hmal'), ('a3abut', 'a3abut'), ('methylbenz', 'methylbenz'), ('d-asp', 'd-asp'), ('leu', 'leu'), ('ser', 'ser'), ('mmal', 'mmal'), ('choi', 'choi'), ('DHCH', 'DHCH'), ('butmal', 'butmal'), ('beta-OH-asp', 'beta-OH-asp'), ('dap', 'dap'), ('2metbut', '2metbut'), ('kyn', 'kyn'), ('lipopep-8D1-1', 'lipopep-8D1-1'), ('gln', 'gln'), ('lys', 'lys'), ('met', 'met'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('2356-OH-me-benz', '2356-OH-me-benz'), ('d-ile', 'd-ile'), ('d-tyr', 'd-tyr'), ('emal', 'emal'), ('tyr', 'tyr'), ('m-tyr', 'm-tyr'), ('arg-AA', 'arg-AA'), ('dhb', 'dhb'), ('d-glu', 'd-glu'), ('3cl-tyr', '3cl-tyr'), ('vinylcinnamoyl', 'vinylcinnamoyl'), ('d-thr', 'd-thr'), ('allylmal', 'allylmal'), ('d-his', 'd-his'), ('me-tyr', 'me-tyr'), ('AHBA', 'AHBA'), ('DHCHene', 'DHCHene'), ('dpg', 'dpg'), ('Acetyl-CoA', 'Acetyl-CoA'), ('guan', 'guan'), ('benz', 'benz'), ('alpha-OH-phe', 'alpha-OH-phe'), ('hpg', 'hpg'), ('isobut', 'isobut'), ('heronamide-1', 'heronamide-1'), ('pip', 'pip'), ('gamma-OH-lys', 'gamma-OH-lys'), ('me-glu', 'me-glu'), ('plac', 'plac'), ('d-leu', 'd-leu'), ('propylamine', 'propylamine'), ('gly', 'gly'), ('beta-amino-glu', 'beta-amino-glu'), ('ml-449-1', 'ml-449-1'), ('d-lys', 'd-lys'), ('2-oxobutmal', '2-oxobutmal'), ('hse', 'hse'), ('me-asp', 'me-asp'), ('d-ser', 'd-ser'), ('2-etmalonamyl', '2-etmalonamyl'), ('his', 'his'), ('d-asn', 'd-asn'), ('d-ala', 'd-ala'), ('d-trp', 'd-trp'), ('3-me-hexmal', '3-me-hexmal'), ('alpha-OH-htyr', 'alpha-OH-htyr'), ('be-14106-1', 'be-14106-1'), ('o-hydroxybenz', 'o-hydroxybenz'), ('DCP', 'DCP'), ('cin', 'cin'), ('14C-FA', '14C-FA'), ('methylbenz-val', 'methylbenz-val'), ('butylamine', 'butylamine'), ('asp-2', 'asp-2'), ('d-glu-2', 'd-glu-2'), ('N/A', 'N/A'), ('pyr', 'pyr'), ('PNBA', 'PNBA'), ('shikimic_acid', 'shikimic_acid')], default='gly', max_length=25)),
                ('type', models.CharField(choices=[('none', 'none'), ('oxidation', 'oxidation'), ('reduction', 'reduction')], default='none', max_length=10)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='ACP',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('substrate', models.CharField(choices=[('thr', 'thr'), ('prop', 'prop'), ('isoval', 'isoval'), ('me-pro', 'me-pro'), ('2aminopent', '2aminopent'), ('dab', 'dab'), ('6-me-hexyl-thr', '6-me-hexyl-thr'), ('phe', 'phe'), ('beta-amino-phe', 'beta-amino-phe'), ('d-arg', 'd-arg'), ('d-cys', 'd-cys'), ('cemal', 'cemal'), ('AAnon', 'AAnon'), ('aba', 'aba'), ('10C-FA', '10C-FA'), ('beta-OH-tyr', 'beta-OH-tyr'), ('N-OH-orn', 'N-OH-orn'), ('mxmal_ACP', 'mxmal_ACP'), ('ema', 'ema'), ('orn', 'orn'), ('CHC-CoA', 'CHC-CoA'), ('butylguanidine', 'butylguanidine'), ('mthz', 'mthz'), ('asp', 'asp'), ('pro', 'pro'), ('3measp', '3measp'), ('cremimycin1', 'cremimycin1'), ('fatty_acid', 'fatty_acid'), ('hpla', 'hpla'), ('me-PABA', 'me-PABA'), ('mxmal', 'mxmal'), ('arg', 'arg'), ('d-val', 'd-val'), ('ile', 'ile'), ('trp', 'trp'), ('beta-OH-asn', 'beta-OH-asn'), ('bmt', 'bmt'), ('8C-AA', '8C-AA'), ('asn', 'asn'), ('mal', 'mal'), ('htyr', 'htyr'), ('ethylguanidine', 'ethylguanidine'), ('d-gln', 'd-gln'), ('cyclopentene', 'cyclopentene'), ('16C-FA', '16C-FA'), ('d-pro', 'd-pro'), ('d-met', 'd-met'), ('NH2', 'NH2'), ('piperazic', 'piperazic'), ('3aminobut', '3aminobut'), ('cys', 'cys'), ('PABA', 'PABA'), ('d-phe', 'd-phe'), ('glu', 'glu'), ('mpro', 'mpro'), ('val', 'val'), ('ala', 'ala'), ('end', 'end'), ('a3abut', 'a3abut'), ('methylbenz', 'methylbenz'), ('d-asp', 'd-asp'), ('leu', 'leu'), ('ser', 'ser'), ('mmal', 'mmal'), ('DHCH', 'DHCH'), ('choi', 'choi'), ('butmal', 'butmal'), ('beta-OH-asp', 'beta-OH-asp'), ('dap', 'dap'), ('2metbut', '2metbut'), ('kyn', 'kyn'), ('lipopep-8D1-1', 'lipopep-8D1-1'), ('gln', 'gln'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('2356-OH-me-benz', '2356-OH-me-benz'), ('lys', 'lys'), ('met', 'met'), ('d-ile', 'd-ile'), ('d-tyr', 'd-tyr'), ('tyr', 'tyr'), ('m-tyr', 'm-tyr'), ('arg-AA', 'arg-AA'), ('dhb', 'dhb'), ('d-glu', 'd-glu'), ('3cl-tyr', '3cl-tyr'), ('vinylcinnamoyl', 'vinylcinnamoyl'), ('d-thr', 'd-thr'), ('AHBA', 'AHBA'), ('d-his', 'd-his'), ('me-tyr', 'me-tyr'), ('DHCHene', 'DHCHene'), ('dpg', 'dpg'), ('Acetyl-CoA', 'Acetyl-CoA'), ('guan', 'guan'), ('benz', 'benz'), ('alpha-OH-phe', 'alpha-OH-phe'), ('hpg', 'hpg'), ('isobut', 'isobut'), ('heronamide-1', 'heronamide-1'), ('pip', 'pip'), ('gamma-OH-lys', 'gamma-OH-lys'), ('me-glu', 'me-glu'), ('plac', 'plac'), ('d-leu', 'd-leu'), ('propylamine', 'propylamine'), ('ml-449-1', 'ml-449-1'), ('gly', 'gly'), ('beta-amino-glu', 'beta-amino-glu'), ('d-lys', 'd-lys'), ('hse', 'hse'), ('2-etmalonamyl', '2-etmalonamyl'), ('d-ser', 'd-ser'), ('me-asp', 'me-asp'), ('his', 'his'), ('d-asn', 'd-asn'), ('d-ala', 'd-ala'), ('d-trp', 'd-trp'), ('alpha-OH-htyr', 'alpha-OH-htyr'), ('be-14106-1', 'be-14106-1'), ('o-hydroxybenz', 'o-hydroxybenz'), ('DCP', 'DCP'), ('cin', 'cin'), ('14C-FA', '14C-FA'), ('butylamine', 'butylamine'), ('methylbenz-val', 'methylbenz-val'), ('asp-2', 'asp-2'), ('d-glu-2', 'd-glu-2'), ('N/A', 'N/A'), ('pyr', 'pyr'), ('PNBA', 'PNBA'), ('shikimic_acid', 'shikimic_acid')], default=None, max_length=20)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='AOX',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='AT',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('substrate', models.CharField(choices=[('thr', 'thr'), ('prop', 'prop'), ('isoval', 'isoval'), ('me-pro', 'me-pro'), ('2aminopent', '2aminopent'), ('dab', 'dab'), ('6-me-hexyl-thr', '6-me-hexyl-thr'), ('phe', 'phe'), ('beta-amino-phe', 'beta-amino-phe'), ('d-arg', 'd-arg'), ('d-cys', 'd-cys'), ('cemal', 'cemal'), ('AAnon', 'AAnon'), ('aba', 'aba'), ('10C-FA', '10C-FA'), ('beta-OH-tyr', 'beta-OH-tyr'), ('N-OH-orn', 'N-OH-orn'), ('mxmal_ACP', 'mxmal_ACP'), ('ema', 'ema'), ('orn', 'orn'), ('CHC-CoA', 'CHC-CoA'), ('butylguanidine', 'butylguanidine'), ('mthz', 'mthz'), ('asp', 'asp'), ('pro', 'pro'), ('isobutmal', 'isobutmal'), ('hpla', 'hpla'), ('me-PABA', 'me-PABA'), ('3measp', '3measp'), ('fatty_acid', 'fatty_acid'), ('cremimycin1', 'cremimycin1'), ('mxmal', 'mxmal'), ('arg', 'arg'), ('d-val', 'd-val'), ('ile', 'ile'), ('trp', 'trp'), ('beta-OH-asn', 'beta-OH-asn'), ('bmt', 'bmt'), ('8C-AA', '8C-AA'), ('asn', 'asn'), ('mal', 'mal'), ('htyr', 'htyr'), ('ethylguanidine', 'ethylguanidine'), ('d-gln', 'd-gln'), ('cyclopentene', 'cyclopentene'), ('d-met', 'd-met'), ('d-pro', 'd-pro'), ('piperazic', 'piperazic'), ('NH2', 'NH2'), ('16C-FA', '16C-FA'), ('d-phe', 'd-phe'), ('cys', 'cys'), ('PABA', 'PABA'), ('3aminobut', '3aminobut'), ('D-isobutmal', 'D-isobutmal'), ('glu', 'glu'), ('mpro', 'mpro'), ('val', 'val'), ('hexmal', 'hexmal'), ('ala', 'ala'), ('end', 'end'), ('hmal', 'hmal'), ('a3abut', 'a3abut'), ('methylbenz', 'methylbenz'), ('d-asp', 'd-asp'), ('leu', 'leu'), ('ser', 'ser'), ('mmal', 'mmal'), ('choi', 'choi'), ('DHCH', 'DHCH'), ('butmal', 'butmal'), ('beta-OH-asp', 'beta-OH-asp'), ('dap', 'dap'), ('2metbut', '2metbut'), ('kyn', 'kyn'), ('lipopep-8D1-1', 'lipopep-8D1-1'), ('gln', 'gln'), ('lys', 'lys'), ('met', 'met'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('2356-OH-me-benz', '2356-OH-me-benz'), ('d-ile', 'd-ile'), ('d-tyr', 'd-tyr'), ('emal', 'emal'), ('tyr', 'tyr'), ('m-tyr', 'm-tyr'), ('arg-AA', 'arg-AA'), ('dhb', 'dhb'), ('d-glu', 'd-glu'), ('3cl-tyr', '3cl-tyr'), ('vinylcinnamoyl', 'vinylcinnamoyl'), ('d-thr', 'd-thr'), ('allylmal', 'allylmal'), ('d-his', 'd-his'), ('me-tyr', 'me-tyr'), ('AHBA', 'AHBA'), ('DHCHene', 'DHCHene'), ('dpg', 'dpg'), ('Acetyl-CoA', 'Acetyl-CoA'), ('guan', 'guan'), ('benz', 'benz'), ('alpha-OH-phe', 'alpha-OH-phe'), ('hpg', 'hpg'), ('isobut', 'isobut'), ('heronamide-1', 'heronamide-1'), ('pip', 'pip'), ('gamma-OH-lys', 'gamma-OH-lys'), ('me-glu', 'me-glu'), ('plac', 'plac'), ('d-leu', 'd-leu'), ('propylamine', 'propylamine'), ('gly', 'gly'), ('beta-amino-glu', 'beta-amino-glu'), ('ml-449-1', 'ml-449-1'), ('d-lys', 'd-lys'), ('2-oxobutmal', '2-oxobutmal'), ('hse', 'hse'), ('me-asp', 'me-asp'), ('d-ser', 'd-ser'), ('2-etmalonamyl', '2-etmalonamyl'), ('his', 'his'), ('d-asn', 'd-asn'), ('d-ala', 'd-ala'), ('d-trp', 'd-trp'), ('3-me-hexmal', '3-me-hexmal'), ('alpha-OH-htyr', 'alpha-OH-htyr'), ('be-14106-1', 'be-14106-1'), ('o-hydroxybenz', 'o-hydroxybenz'), ('DCP', 'DCP'), ('cin', 'cin'), ('14C-FA', '14C-FA'), ('methylbenz-val', 'methylbenz-val'), ('butylamine', 'butylamine'), ('asp-2', 'asp-2'), ('d-glu-2', 'd-glu-2'), ('N/A', 'N/A'), ('pyr', 'pyr'), ('PNBA', 'PNBA'), ('shikimic_acid', 'shikimic_acid')], default='mal', max_length=20)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('type', models.CharField(choices=[('Unknown', 'Unknown'), ('Starter', 'Starter'), ('LCL', 'LCL'), ('DCL', 'DCL'), ('Dual', 'Dual'), ('Glycopeptide', 'Glycopeptide')], default=None, max_length=12)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='CAL',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('substrate', models.CharField(choices=[('thr', 'thr'), ('prop', 'prop'), ('isoval', 'isoval'), ('me-pro', 'me-pro'), ('2aminopent', '2aminopent'), ('dab', 'dab'), ('6-me-hexyl-thr', '6-me-hexyl-thr'), ('phe', 'phe'), ('beta-amino-phe', 'beta-amino-phe'), ('d-arg', 'd-arg'), ('d-cys', 'd-cys'), ('cemal', 'cemal'), ('AAnon', 'AAnon'), ('aba', 'aba'), ('10C-FA', '10C-FA'), ('beta-OH-tyr', 'beta-OH-tyr'), ('N-OH-orn', 'N-OH-orn'), ('mxmal_ACP', 'mxmal_ACP'), ('ema', 'ema'), ('orn', 'orn'), ('CHC-CoA', 'CHC-CoA'), ('butylguanidine', 'butylguanidine'), ('mthz', 'mthz'), ('asp', 'asp'), ('pro', 'pro'), ('isobutmal', 'isobutmal'), ('hpla', 'hpla'), ('me-PABA', 'me-PABA'), ('3measp', '3measp'), ('fatty_acid', 'fatty_acid'), ('cremimycin1', 'cremimycin1'), ('mxmal', 'mxmal'), ('arg', 'arg'), ('d-val', 'd-val'), ('ile', 'ile'), ('trp', 'trp'), ('beta-OH-asn', 'beta-OH-asn'), ('bmt', 'bmt'), ('8C-AA', '8C-AA'), ('asn', 'asn'), ('mal', 'mal'), ('htyr', 'htyr'), ('ethylguanidine', 'ethylguanidine'), ('d-gln', 'd-gln'), ('cyclopentene', 'cyclopentene'), ('d-met', 'd-met'), ('d-pro', 'd-pro'), ('piperazic', 'piperazic'), ('NH2', 'NH2'), ('16C-FA', '16C-FA'), ('d-phe', 'd-phe'), ('cys', 'cys'), ('PABA', 'PABA'), ('3aminobut', '3aminobut'), ('D-isobutmal', 'D-isobutmal'), ('glu', 'glu'), ('mpro', 'mpro'), ('val', 'val'), ('hexmal', 'hexmal'), ('ala', 'ala'), ('end', 'end'), ('hmal', 'hmal'), ('a3abut', 'a3abut'), ('methylbenz', 'methylbenz'), ('d-asp', 'd-asp'), ('leu', 'leu'), ('ser', 'ser'), ('mmal', 'mmal'), ('choi', 'choi'), ('DHCH', 'DHCH'), ('butmal', 'butmal'), ('beta-OH-asp', 'beta-OH-asp'), ('dap', 'dap'), ('2metbut', '2metbut'), ('kyn', 'kyn'), ('lipopep-8D1-1', 'lipopep-8D1-1'), ('gln', 'gln'), ('lys', 'lys'), ('met', 'met'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('2356-OH-me-benz', '2356-OH-me-benz'), ('d-ile', 'd-ile'), ('d-tyr', 'd-tyr'), ('emal', 'emal'), ('tyr', 'tyr'), ('m-tyr', 'm-tyr'), ('arg-AA', 'arg-AA'), ('dhb', 'dhb'), ('d-glu', 'd-glu'), ('3cl-tyr', '3cl-tyr'), ('vinylcinnamoyl', 'vinylcinnamoyl'), ('d-thr', 'd-thr'), ('allylmal', 'allylmal'), ('d-his', 'd-his'), ('me-tyr', 'me-tyr'), ('AHBA', 'AHBA'), ('DHCHene', 'DHCHene'), ('dpg', 'dpg'), ('Acetyl-CoA', 'Acetyl-CoA'), ('guan', 'guan'), ('benz', 'benz'), ('alpha-OH-phe', 'alpha-OH-phe'), ('hpg', 'hpg'), ('isobut', 'isobut'), ('heronamide-1', 'heronamide-1'), ('pip', 'pip'), ('gamma-OH-lys', 'gamma-OH-lys'), ('me-glu', 'me-glu'), ('plac', 'plac'), ('d-leu', 'd-leu'), ('propylamine', 'propylamine'), ('gly', 'gly'), ('beta-amino-glu', 'beta-amino-glu'), ('ml-449-1', 'ml-449-1'), ('d-lys', 'd-lys'), ('2-oxobutmal', '2-oxobutmal'), ('hse', 'hse'), ('me-asp', 'me-asp'), ('d-ser', 'd-ser'), ('2-etmalonamyl', '2-etmalonamyl'), ('his', 'his'), ('d-asn', 'd-asn'), ('d-ala', 'd-ala'), ('d-trp', 'd-trp'), ('3-me-hexmal', '3-me-hexmal'), ('alpha-OH-htyr', 'alpha-OH-htyr'), ('be-14106-1', 'be-14106-1'), ('o-hydroxybenz', 'o-hydroxybenz'), ('DCP', 'DCP'), ('cin', 'cin'), ('14C-FA', '14C-FA'), ('methylbenz-val', 'methylbenz-val'), ('butylamine', 'butylamine'), ('asp-2', 'asp-2'), ('d-glu-2', 'd-glu-2'), ('N/A', 'N/A'), ('pyr', 'pyr'), ('PNBA', 'PNBA'), ('shikimic_acid', 'shikimic_acid')], default='mal', max_length=20)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='cMT',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='Cy',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='DH',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='E',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='ER',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='F',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='KR',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField()),
                ('type', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A', 'A'), ('B1', 'B1'), ('B2', 'B2'), ('B', 'B'), ('C1', 'C1'), ('C2', 'C2'), ('U', 'U')], default=None, max_length=2)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='KS',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='nMT',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='oMT',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='PCP',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='R',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('alcohol', 'alcohol'), ('aldehyde', 'aldehyde'), ('unusual: see notes', 'unusual: see notes')], default='unusual: see notes', max_length=18)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='TE',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('cyclic', models.BooleanField()),
                ('ring', models.IntegerField(default=0)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='X',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='Subunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('genbankAccession', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=2000)),
                ('start', models.PositiveIntegerField()),
                ('stop', models.PositiveIntegerField()),
                ('sequence', models.TextField()),
                ('acc', models.TextField()),
                ('acc20', models.CharField(max_length=1000000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('accPlotFile', models.ImageField(upload_to='accplots')),
                ('ss', models.TextField()),
                ('ss8', models.TextField()),
                ('ssPlotFile', models.ImageField(upload_to='ssplots')),
                ('sense', models.CharField(max_length=3)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pks.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Standalone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=2000)),
                ('start', models.PositiveIntegerField()),
                ('stop', models.PositiveIntegerField()),
                ('sequence', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pks.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('loading', models.BooleanField()),
                ('terminal', models.BooleanField()),
                ('iterations', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounddb.Compound')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pks.Subunit')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pks.Module'),
        ),
    ]
