# Generated by Django 2.2.4 on 2020-11-16 22:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounddb', '0002_rdkit_cartridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mibigAccession', models.CharField(max_length=100)),
                ('genbankAccession', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sequence', models.TextField()),
                ('knownProductSmiles', models.TextField()),
                ('knownProductMCS', models.TextField()),
                ('knownProductSource', models.TextField(default='unknown')),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('stop', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ACP',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='AT',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('substrate', models.CharField(choices=[('2metbut', '2metbut'), ('hmal', 'hmal'), ('ema', 'ema'), ('shikimic_acid', 'shikimic_acid'), ('emal', 'emal'), ('isobutmal', 'isobutmal'), ('mthz', 'mthz'), ('3measp', '3measp'), ('fatty_acid', 'fatty_acid'), ('AHBA', 'AHBA'), ('a3abut', 'a3abut'), ('hexmal', 'hexmal'), ('cemal', 'cemal'), ('D-isobutmal', 'D-isobutmal'), ('isoval', 'isoval'), ('mxmal_ACP', 'mxmal_ACP'), ('plac', 'plac'), ('cin', 'cin'), ('butmal', 'butmal'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('DCP', 'DCP'), ('N/A', 'N/A'), ('allylmal', 'allylmal'), ('AAnon', 'AAnon'), ('PNBA', 'PNBA'), ('cyclopentene', 'cyclopentene'), ('pyr', 'pyr'), ('NH2', 'NH2'), ('prop', 'prop'), ('DHCHene', 'DHCHene'), ('DHCH', 'DHCH'), ('Acetyl-CoA', 'Acetyl-CoA'), ('mxmal', 'mxmal'), ('benz', 'benz'), ('mal', 'mal'), ('isobut', 'isobut'), ('mmal', 'mmal'), ('PABA', 'PABA'), ('CHC-CoA', 'CHC-CoA'), ('guan', 'guan')], default='mal', max_length=20)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='CAL',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('substrate', models.CharField(choices=[('2metbut', '2metbut'), ('hmal', 'hmal'), ('ema', 'ema'), ('shikimic_acid', 'shikimic_acid'), ('emal', 'emal'), ('isobutmal', 'isobutmal'), ('mthz', 'mthz'), ('3measp', '3measp'), ('fatty_acid', 'fatty_acid'), ('AHBA', 'AHBA'), ('a3abut', 'a3abut'), ('hexmal', 'hexmal'), ('cemal', 'cemal'), ('D-isobutmal', 'D-isobutmal'), ('isoval', 'isoval'), ('mxmal_ACP', 'mxmal_ACP'), ('plac', 'plac'), ('cin', 'cin'), ('butmal', 'butmal'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('DCP', 'DCP'), ('N/A', 'N/A'), ('allylmal', 'allylmal'), ('AAnon', 'AAnon'), ('PNBA', 'PNBA'), ('cyclopentene', 'cyclopentene'), ('pyr', 'pyr'), ('NH2', 'NH2'), ('prop', 'prop'), ('DHCHene', 'DHCHene'), ('DHCH', 'DHCH'), ('Acetyl-CoA', 'Acetyl-CoA'), ('mxmal', 'mxmal'), ('benz', 'benz'), ('mal', 'mal'), ('isobut', 'isobut'), ('mmal', 'mmal'), ('PABA', 'PABA'), ('CHC-CoA', 'CHC-CoA'), ('guan', 'guan')], default='mal', max_length=20)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='cMT',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='DH',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='ER',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='KR',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField()),
                ('type', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A', 'A'), ('B1', 'B1'), ('B2', 'B2'), ('B', 'B'), ('C1', 'C1'), ('C2', 'C2'), ('U', 'U')], default=None, max_length=2)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='KS',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='oMT',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='PCP',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='TE',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('cyclic', models.BooleanField()),
                ('ring', models.IntegerField(default=0)),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='Subunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('genbankAccession', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=2000)),
                ('start', models.PositiveIntegerField()),
                ('stop', models.PositiveIntegerField()),
                ('sequence', models.TextField()),
                ('acc', models.TextField()),
                ('acc20', models.CharField(max_length=1000000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('accPlotFile', models.ImageField(upload_to='accplots')),
                ('ss', models.TextField()),
                ('ss8', models.TextField()),
                ('ssPlotFile', models.ImageField(upload_to='ssplots')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pks.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Standalone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=2000)),
                ('start', models.PositiveIntegerField()),
                ('stop', models.PositiveIntegerField()),
                ('sequence', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pks.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('loading', models.BooleanField()),
                ('terminal', models.BooleanField()),
                ('iterations', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounddb.Compound')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pks.Subunit')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pks.Module'),
        ),
    ]
