# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACP',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
            ],
            bases=('pks.domain',),
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='genbankVersion',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='mibigVersion',
        ),
        migrations.AlterField(
            model_name='atl',
            name='starter',
            field=models.CharField(choices=[('mal', 'mal'), ('mmal', 'mmal'), ('mxmal', 'mxmal'), ('cemal', 'cemal'), ('Acetyl-CoA', 'Acetyl-CoA'), ('prop', 'prop'), ('isobut', 'isobut'), ('2metbut', '2metbut'), ('CHC-CoA', 'CHC-CoA'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), (None, 'N/A')], default='mal', max_length=20),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='mibigAccession',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
