# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='iterations',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='te',
            name='ring',
            field=models.IntegerField(default=0),
        ),
    ]
