# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunit',
            name='acc20',
            field=models.CommaSeparatedIntegerField(max_length=1000000),
        ),
    ]
