# Generated by Django 2.2.3 on 2019-10-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='at',
            name='substrate',
            field=models.CharField(choices=[('DCP', 'DCP'), ('cin', 'cin'), ('DHCH', 'DHCH'), ('ema', 'ema'), ('isobutmal', 'isobutmal'), ('mthz', 'mthz'), ('PNBA', 'PNBA'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('2metbut', '2metbut'), ('prop', 'prop'), ('mxmal', 'mxmal'), ('butmal', 'butmal'), ('pyr', 'pyr'), ('isobut', 'isobut'), ('mxmal_ACP', 'mxmal_ACP'), ('PABA', 'PABA'), ('emal', 'emal'), ('cyclopentene', 'cyclopentene'), ('mmal', 'mmal'), ('3measp', '3measp'), ('NH2', 'NH2'), ('D-isobutmal', 'D-isobutmal'), ('isoval', 'isoval'), ('cemal', 'cemal'), ('guan', 'guan'), ('fatty_acid', 'fatty_acid'), ('DHCHene', 'DHCHene'), ('a3abut', 'a3abut'), ('hexmal', 'hexmal'), ('allylmal', 'allylmal'), ('AAnon', 'AAnon'), ('AHBA', 'AHBA'), ('N/A', 'N/A'), ('plac', 'plac'), ('shikimic_acid', 'shikimic_acid'), ('mal', 'mal'), ('hmal', 'hmal'), ('CHC-CoA', 'CHC-CoA'), ('benz', 'benz'), ('Acetyl-CoA', 'Acetyl-CoA')], default='mal', max_length=20),
        ),
        migrations.AlterField(
            model_name='cal',
            name='substrate',
            field=models.CharField(choices=[('DCP', 'DCP'), ('cin', 'cin'), ('DHCH', 'DHCH'), ('ema', 'ema'), ('isobutmal', 'isobutmal'), ('mthz', 'mthz'), ('PNBA', 'PNBA'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('2metbut', '2metbut'), ('prop', 'prop'), ('mxmal', 'mxmal'), ('butmal', 'butmal'), ('pyr', 'pyr'), ('isobut', 'isobut'), ('mxmal_ACP', 'mxmal_ACP'), ('PABA', 'PABA'), ('emal', 'emal'), ('cyclopentene', 'cyclopentene'), ('mmal', 'mmal'), ('3measp', '3measp'), ('NH2', 'NH2'), ('D-isobutmal', 'D-isobutmal'), ('isoval', 'isoval'), ('cemal', 'cemal'), ('guan', 'guan'), ('fatty_acid', 'fatty_acid'), ('DHCHene', 'DHCHene'), ('a3abut', 'a3abut'), ('hexmal', 'hexmal'), ('allylmal', 'allylmal'), ('AAnon', 'AAnon'), ('AHBA', 'AHBA'), ('N/A', 'N/A'), ('plac', 'plac'), ('shikimic_acid', 'shikimic_acid'), ('mal', 'mal'), ('hmal', 'hmal'), ('CHC-CoA', 'CHC-CoA'), ('benz', 'benz'), ('Acetyl-CoA', 'Acetyl-CoA')], default='mal', max_length=20),
        ),
    ]
