# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='at',
            name='substrate',
            field=models.CharField(choices=[('mal', 'mal'), ('mmal', 'mmal'), ('mxmal', 'mxmal'), ('emal', 'emal'), ('cemal', 'cemal'), ('Acetyl-CoA', 'Acetyl-CoA'), ('prop', 'prop'), ('isobut', 'isobut'), ('2metbut', '2metbut'), ('CHC-CoA', 'CHC-CoA'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('N/A', 'N/A')], default='mal', max_length=20),
        ),
    ]
