# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0002_auto_20170605_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunit',
            name='accPlot',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subunit',
            name='ssPlot',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
