# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0002_auto_20170314_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='cMT',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField()),
            ],
            bases=('pks.domain',),
        ),
        migrations.CreateModel(
            name='oMT',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('active', models.BooleanField()),
            ],
            bases=('pks.domain',),
        ),
    ]
