# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounddb', '0001_initial'),
        ('pks', '0002_auto_20170323_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='compounddb.Compound'),
        ),
    ]
