# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0003_module_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounddb.Compound'),
        ),
    ]
