# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0003_auto_20170608_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAL',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
                ('substrate', models.CharField(choices=[('mal', 'mal'), ('mmal', 'mmal'), ('mxmal', 'mxmal'), ('emal', 'emal'), ('cemal', 'cemal'), ('butmal', 'butmal'), ('hexmal', 'hexmal'), ('Acetyl-CoA', 'Acetyl-CoA'), ('prop', 'prop'), ('isobut', 'isobut'), ('2metbut', '2metbut'), ('CHC-CoA', 'CHC-CoA'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('cyclopentene', 'cyclopentene'), ('N/A', 'N/A')], default='mal', max_length=20)),
            ],
            bases=('pks.domain',),
        ),
        migrations.AlterField(
            model_name='at',
            name='substrate',
            field=models.CharField(choices=[('mal', 'mal'), ('mmal', 'mmal'), ('mxmal', 'mxmal'), ('emal', 'emal'), ('cemal', 'cemal'), ('butmal', 'butmal'), ('hexmal', 'hexmal'), ('Acetyl-CoA', 'Acetyl-CoA'), ('prop', 'prop'), ('isobut', 'isobut'), ('2metbut', '2metbut'), ('CHC-CoA', 'CHC-CoA'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('cyclopentene', 'cyclopentene'), ('N/A', 'N/A')], default='mal', max_length=20),
        ),
        migrations.AlterField(
            model_name='kr',
            name='type',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A', 'A'), ('B1', 'B1'), ('B2', 'B2'), ('B', 'B'), ('C1', 'C1'), ('C2', 'C2'), ('U', 'U')], default=None, max_length=2),
        ),
    ]
