# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0003_cmt_omt'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunit',
            name='genbankAccession',
            field=models.CharField(default='blah', max_length=2000, unique=True),
            preserve_default=False,
        ),
    ]
