# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0004_auto_20170803_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subunit',
            name='ssPlot',
        ),
        migrations.AddField(
            model_name='subunit',
            name='accPlotFile',
            field=models.ImageField(default='', upload_to='accplots'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subunit',
            name='ssPlotFile',
            field=models.ImageField(default='', upload_to='ssplots'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cal',
            name='substrate',
            field=models.CharField(choices=[('mal', 'mal'), ('mmal', 'mmal'), ('mxmal', 'mxmal'), ('emal', 'emal'), ('cemal', 'cemal'), ('butmal', 'butmal'), ('hexmal', 'hexmal'), ('Acetyl-CoA', 'Acetyl-CoA'), ('prop', 'prop'), ('isobut', 'isobut'), ('2metbut', '2metbut'), ('CHC-CoA', 'CHC-CoA'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('cyclopentene', 'cyclopentene'), ('shikimic_acid', 'shikimic_acid'), ('AHBA', 'AHBA'), ('fatty_acid', 'fatty_acid'), ('NH2', 'NH2'), ('N/A', 'N/A')], default='mal', max_length=20),
        ),
    ]
