# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounddb', '0001_initial'),
        ('pks', '0004_auto_20170324_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='knownProduct',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounddb.Compound'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='knownProductSource',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='module',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounddb.Compound'),
        ),
    ]
