# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0005_auto_20170314_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atl',
            name='domain_ptr',
        ),
        migrations.AlterField(
            model_name='at',
            name='extender',
            field=models.CharField(choices=[('mal', 'mal'), ('emal', 'emal'), ('mmal', 'mmal'), ('mxmal', 'mxmal'), ('cemal', 'cemal'), ('Acetyl-CoA', 'Acetyl-CoA'), ('prop', 'prop'), ('isobut', 'isobut'), ('2metbut', '2metbut'), ('CHC-CoA', 'CHC-CoA'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), (None, 'N/A')], default='mal', max_length=20),
        ),
        migrations.DeleteModel(
            name='ATL',
        ),
    ]
