# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0005_auto_20170808_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subunit',
            name='accPlot',
        ),
    ]
