# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0006_auto_20170314_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCP',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pks.Domain')),
            ],
            bases=('pks.domain',),
        ),
        migrations.RenameField(
            model_name='at',
            old_name='extender',
            new_name='substrate',
        ),
        migrations.AlterField(
            model_name='cmt',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dh',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='er',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kr',
            name='type',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), (None, 'U')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='omt',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
