# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0006_remove_subunit_accplot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='at',
            name='substrate',
            field=models.CharField(choices=[('ema', 'ema'), ('prop', 'prop'), ('mthz', 'mthz'), ('CHC-CoA', 'CHC-CoA'), ('benz', 'benz'), ('isobutmal', 'isobutmal'), ('isobut', 'isobut'), ('Acetyl-CoA', 'Acetyl-CoA'), ('NH2', 'NH2'), ('PNBA', 'PNBA'), ('cyclopentene', 'cyclopentene'), ('a3abut', 'a3abut'), ('mmal', 'mmal'), ('mal', 'mal'), ('PABA', 'PABA'), ('guan', 'guan'), ('mxmal_ACP', 'mxmal_ACP'), ('plac', 'plac'), ('fatty_acid', 'fatty_acid'), ('DHCHene', 'DHCHene'), ('AAnon', 'AAnon'), ('cin', 'cin'), ('emal', 'emal'), ('butmal', 'butmal'), ('3measp', '3measp'), ('D-isobutmal', 'D-isobutmal'), ('hmal', 'hmal'), ('cemal', 'cemal'), ('pyr', 'pyr'), ('DCP', 'DCP'), ('isoval', 'isoval'), ('hexmal', 'hexmal'), ('AHBA', 'AHBA'), ('N/A', 'N/A'), ('shikimic_acid', 'shikimic_acid'), ('DHCH', 'DHCH'), ('mxmal', 'mxmal'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('2metbut', '2metbut'), ('allylmal', 'allylmal')], default='mal', max_length=20),
        ),
        migrations.AlterField(
            model_name='cal',
            name='substrate',
            field=models.CharField(choices=[('ema', 'ema'), ('prop', 'prop'), ('mthz', 'mthz'), ('CHC-CoA', 'CHC-CoA'), ('benz', 'benz'), ('isobutmal', 'isobutmal'), ('isobut', 'isobut'), ('Acetyl-CoA', 'Acetyl-CoA'), ('NH2', 'NH2'), ('PNBA', 'PNBA'), ('cyclopentene', 'cyclopentene'), ('a3abut', 'a3abut'), ('mmal', 'mmal'), ('mal', 'mal'), ('PABA', 'PABA'), ('guan', 'guan'), ('mxmal_ACP', 'mxmal_ACP'), ('plac', 'plac'), ('fatty_acid', 'fatty_acid'), ('DHCHene', 'DHCHene'), ('AAnon', 'AAnon'), ('cin', 'cin'), ('emal', 'emal'), ('butmal', 'butmal'), ('3measp', '3measp'), ('D-isobutmal', 'D-isobutmal'), ('hmal', 'hmal'), ('cemal', 'cemal'), ('pyr', 'pyr'), ('DCP', 'DCP'), ('isoval', 'isoval'), ('hexmal', 'hexmal'), ('AHBA', 'AHBA'), ('N/A', 'N/A'), ('shikimic_acid', 'shikimic_acid'), ('DHCH', 'DHCH'), ('mxmal', 'mxmal'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('2metbut', '2metbut'), ('allylmal', 'allylmal')], default='mal', max_length=20),
        ),
    ]
