# Generated by Django 2.2.3 on 2021-11-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pks', '0011_auto_20211031_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunit',
            name='sense',
            field=models.CharField(default='(+)', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='a',
            name='substrate',
            field=models.CharField(choices=[('phe', 'phe'), ('lys', 'lys'), ('prop', 'prop'), ('orn', 'orn'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('guan', 'guan'), ('DHCH', 'DHCH'), ('pro', 'pro'), ('asp', 'asp'), ('pip', 'pip'), ('CHC-CoA', 'CHC-CoA'), ('3measp', '3measp'), ('leu', 'leu'), ('shikimic_acid', 'shikimic_acid'), ('gly', 'gly'), ('ile', 'ile'), ('NH2', 'NH2'), ('hexmal', 'hexmal'), ('mthz', 'mthz'), ('tyr', 'tyr'), ('PNBA', 'PNBA'), ('bmt', 'bmt'), ('isobutmal', 'isobutmal'), ('D-isobutmal', 'D-isobutmal'), ('benz', 'benz'), ('glu', 'glu'), ('DHCHene', 'DHCHene'), ('arg', 'arg'), ('isoval', 'isoval'), ('a3abut', 'a3abut'), ('Acetyl-CoA', 'Acetyl-CoA'), ('met', 'met'), ('mal', 'mal'), ('thr', 'thr'), ('DCP', 'DCP'), ('cemal', 'cemal'), ('d-ala', 'd-ala'), ('ala', 'ala'), ('his', 'his'), ('pyr', 'pyr'), ('ema', 'ema'), ('AAnon', 'AAnon'), ('2metbut', '2metbut'), ('fatty_acid', 'fatty_acid'), ('ser', 'ser'), ('val', 'val'), ('cyclopentene', 'cyclopentene'), ('gln', 'gln'), ('hmal', 'hmal'), ('PABA', 'PABA'), ('allylmal', 'allylmal'), ('plac', 'plac'), ('N/A', 'N/A'), ('mxmal_ACP', 'mxmal_ACP'), ('AHBA', 'AHBA'), ('cys', 'cys'), ('butmal', 'butmal'), ('cin', 'cin'), ('mpro', 'mpro'), ('mxmal', 'mxmal'), ('isobut', 'isobut'), ('hty', 'hty'), ('asn', 'asn'), ('trp', 'trp'), ('emal', 'emal'), ('aba', 'aba'), ('mmal', 'mmal')], default='gly', max_length=25),
        ),
        migrations.AlterField(
            model_name='at',
            name='substrate',
            field=models.CharField(choices=[('phe', 'phe'), ('lys', 'lys'), ('prop', 'prop'), ('orn', 'orn'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('guan', 'guan'), ('DHCH', 'DHCH'), ('pro', 'pro'), ('asp', 'asp'), ('pip', 'pip'), ('CHC-CoA', 'CHC-CoA'), ('3measp', '3measp'), ('leu', 'leu'), ('shikimic_acid', 'shikimic_acid'), ('gly', 'gly'), ('ile', 'ile'), ('NH2', 'NH2'), ('hexmal', 'hexmal'), ('mthz', 'mthz'), ('tyr', 'tyr'), ('PNBA', 'PNBA'), ('bmt', 'bmt'), ('isobutmal', 'isobutmal'), ('D-isobutmal', 'D-isobutmal'), ('benz', 'benz'), ('glu', 'glu'), ('DHCHene', 'DHCHene'), ('arg', 'arg'), ('isoval', 'isoval'), ('a3abut', 'a3abut'), ('Acetyl-CoA', 'Acetyl-CoA'), ('met', 'met'), ('mal', 'mal'), ('thr', 'thr'), ('DCP', 'DCP'), ('cemal', 'cemal'), ('d-ala', 'd-ala'), ('ala', 'ala'), ('his', 'his'), ('pyr', 'pyr'), ('ema', 'ema'), ('AAnon', 'AAnon'), ('2metbut', '2metbut'), ('fatty_acid', 'fatty_acid'), ('ser', 'ser'), ('val', 'val'), ('cyclopentene', 'cyclopentene'), ('gln', 'gln'), ('hmal', 'hmal'), ('PABA', 'PABA'), ('allylmal', 'allylmal'), ('plac', 'plac'), ('N/A', 'N/A'), ('mxmal_ACP', 'mxmal_ACP'), ('AHBA', 'AHBA'), ('cys', 'cys'), ('butmal', 'butmal'), ('cin', 'cin'), ('mpro', 'mpro'), ('mxmal', 'mxmal'), ('isobut', 'isobut'), ('hty', 'hty'), ('asn', 'asn'), ('trp', 'trp'), ('emal', 'emal'), ('aba', 'aba'), ('mmal', 'mmal')], default='mal', max_length=20),
        ),
        migrations.AlterField(
            model_name='cal',
            name='substrate',
            field=models.CharField(choices=[('phe', 'phe'), ('lys', 'lys'), ('prop', 'prop'), ('orn', 'orn'), ('trans-1,2-CPDA', 'trans-1,2-CPDA'), ('guan', 'guan'), ('DHCH', 'DHCH'), ('pro', 'pro'), ('asp', 'asp'), ('pip', 'pip'), ('CHC-CoA', 'CHC-CoA'), ('3measp', '3measp'), ('leu', 'leu'), ('shikimic_acid', 'shikimic_acid'), ('gly', 'gly'), ('ile', 'ile'), ('NH2', 'NH2'), ('hexmal', 'hexmal'), ('mthz', 'mthz'), ('tyr', 'tyr'), ('PNBA', 'PNBA'), ('bmt', 'bmt'), ('isobutmal', 'isobutmal'), ('D-isobutmal', 'D-isobutmal'), ('benz', 'benz'), ('glu', 'glu'), ('DHCHene', 'DHCHene'), ('arg', 'arg'), ('isoval', 'isoval'), ('a3abut', 'a3abut'), ('Acetyl-CoA', 'Acetyl-CoA'), ('met', 'met'), ('mal', 'mal'), ('thr', 'thr'), ('DCP', 'DCP'), ('cemal', 'cemal'), ('d-ala', 'd-ala'), ('ala', 'ala'), ('his', 'his'), ('pyr', 'pyr'), ('ema', 'ema'), ('AAnon', 'AAnon'), ('2metbut', '2metbut'), ('fatty_acid', 'fatty_acid'), ('ser', 'ser'), ('val', 'val'), ('cyclopentene', 'cyclopentene'), ('gln', 'gln'), ('hmal', 'hmal'), ('PABA', 'PABA'), ('allylmal', 'allylmal'), ('plac', 'plac'), ('N/A', 'N/A'), ('mxmal_ACP', 'mxmal_ACP'), ('AHBA', 'AHBA'), ('cys', 'cys'), ('butmal', 'butmal'), ('cin', 'cin'), ('mpro', 'mpro'), ('mxmal', 'mxmal'), ('isobut', 'isobut'), ('hty', 'hty'), ('asn', 'asn'), ('trp', 'trp'), ('emal', 'emal'), ('aba', 'aba'), ('mmal', 'mmal')], default='mal', max_length=20),
        ),
    ]
