# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('inchiKey', models.CharField(max_length=27, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('smiles', models.TextField()),
            ],
        ),
    ]
